In [3]:
import numpy as np
grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [4]:
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [7]:
grades.mean() # Calculating the mean

87.5

In [9]:
grades.sum()/len(grades) # calculating the standard deviation

87.5

In [10]:
np.median(grades) # Calculating the median

88.5

In [11]:
grades.min() # Calculating the minimum grade

75

In [12]:
grades.max() # Calculating the maximum grade

98

In [13]:
np.sort(grades) # Sorting in Ascending other

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [25]:
np.sort(grades)[:: -1] # Sorting in decending other

array([98, 95, 92, 90, 89, 88, 85, 83, 80, 75])

In [26]:
np.argmax(grades) # The index of the highest grade in the array

7

In [30]:
grades[grades > 90] # count the number of students who scored above 90

array([92, 95, 98])

In [31]:
np.mean(grades > 90) * 100 # calculate the percentage of students who scored above 90

30.0

In [32]:
np.mean(grades < 75) * 75 # calculate the percentage of students who scored below 75

0.0

In [37]:
high_performance=grades[grades > 90] #  extract all the grades above 90 and put them in a new array called "high_performers"

In [38]:
high_performance

array([92, 95, 98])

In [39]:
passing_grades=grades[grades > 75] # Create a new array called "passing_grades" that contains all the grades above 75.

In [40]:
passing_grades

array([85, 90, 88, 92, 95, 80, 98, 89, 83])

In [41]:
import numpy as np
passing_grades =np.array([80, 83, 85, 88, 89, 90, 92, 95, 98])

In [42]:
passing_grades

array([80, 83, 85, 88, 89, 90, 92, 95, 98])